baseURL = 'https://blog.jmh-su.com'
languageCode = 'en-us'
title = ''
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[module]
# uncomment line below for temporary local development of module
# replacements = "github.com/lxndrblz/anatole -> ../../anatole"
[[module.imports]]
path = "github.com/lxndrblz/anatole"
disable = false

[params.gitalk]
clientID = "GitHub Application Client ID"
clientSecret = "GitHub Application Client Secret"
repo = "Repository name to store issues"
owner = "GitHub repo owner"
admin = "GitHub repo owner and collaborators, only these guys can initialize gitHub issues"