[[main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"
[[main]]
name = "About"
weight = 300
identifier = "about"
url = "/about/"
[[main]]
name = "Archives"
weight = 300
identifier = "Archives"
url = "/post/"
[[main]]
name = "Portfolio"
weight = 300
identifier = "portfolio"
url = "/portfolio/"