title = "I'M HONG JUNMIN"
author = "洪鈞閔"
description = """
I'm Backend Engineer
Love Share and Learn
"""
profilePicture = "images/profile.jpeg"
favicon = "favicons/"
mainSections = ["post"]
readMore = true
contentratio = 0.7
gtagId = "G-xxxxxx"
[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/junminhong"

[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/junminhong/"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:junminhong1110@gmail.com"