version: "3.7"
services:
  jmh-profile:
    image: klakegg/hugo:0.92.1-ext
    command: server
    container_name: jmh-profile
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    environment:
      - HUGO_ENV="production"
    networks:
      - nginx

networks:
  nginx:
    name: nginx